/********** Inserts **********/

INSERT INTO USER_ROLE VALUES (1,'EMPLOYEE');
INSERT INTO USER_ROLE VALUES (2,'MANAGER');

INSERT INTO USER_T VALUES (0,'PETER','ALAGNA','PALAGNAJR','123456','PETER.ALAGNA@REVATURE.COM',1);
UPDATE USER_T SET U_FIRST_NAME = ?, U_LAST_NAME = ?, U_USER_NAME = ?, U_PASSWORD = ?, U_EMAIL = ?, UR_ID = ? WHERE U_ID = ?;


INSERT INTO REIMBURSEMENT_TYPE VALUES (1,'OTHER');
INSERT INTO REIMBURSEMENT_TYPE VALUES (2,'COURSE');
INSERT INTO REIMBURSEMENT_TYPE VALUES (3,'CERTIFICATION');
INSERT INTO REIMBURSEMENT_TYPE VALUES (4,'TRAVELING');

INSERT INTO REIMBURSEMENT_STATUS VALUES (1,'PENDING');
INSERT INTO REIMBURSEMENT_STATUS VALUES (2,'DECLINED');
INSERT INTO REIMBURSEMENT_STATUS VALUES (3,'APPROVED');